name: Build

on: [ push, pull_request ]

env:
  BUILD_TYPE: "Release"
  GODOT_VERSION: "4.1.1"


jobs:
  build:
    # Latest Ubuntu LTS
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=/usr

      - name: Build
        run: cmake --build . --config $BUILD_TYPE