name: Desktop

on: [ push, pull_request ]

env:
  BUILD_TYPE: "Release"
  GODOT_VERSION: "4.1.1"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Latest Ubuntu LTS
          - os: ubuntu-22.04
            edition: "linux.x86_64"
            preset: "Linux"

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - name: Build
        env:
          GODOT_EDITION: ${{matrix.edition}}
          GODOT_PRESET: ${{matrix.preset}}
        run: python scripts/build.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: xonix
          path: export
