name: Desktop

on: [ push, pull_request ]

env:
  BUILD_TYPE: "Release"
  GODOT_VERSION: "4.1.1"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Latest Ubuntu LTS
          - os: ubuntu-22.04
            edition: "linux.x86_64"
            output: "xonix.x86_64"
          - os: macos-latest
            edition: "macos.universal"
            output: "xonix.zip"

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3

      - name: Cache Godot
        uses: actions/cache@v3
        with:
          path: |
            _deps
            Godot*.zip
          key: godot-${{env.GODOT_VERSION}}-${{matrix.edition}}

      - name: Cache Export Templates
        uses: actions/cache@v3
        with:
          path: Godot*export_templates.tpz
          key: godot-${{env.GODOT_VERSION}}-export-templates

      - name: Download Editor
        run: |
          python3 scripts/download.py editor --godot-version "${{env.GODOT_VERSION}}" --godot-edition "${{matrix.edition}}"
          mv "Godot_v${{env.GODOT_VERSION}}-stable_linux.x86_64" "./game/godot"
          chmod +x "./game/godot"

      - name: Download Export Templates
        run: python3 scripts/download.py export-templates --godot-version "${{env.GODOT_VERSION}}"

      - name: Configure CMake
        run: cmake . -DCMAKE_BUILD_TYPE="${{env.BUILD_TYPE}}"

      - name: Build
        run: cmake --build . --config ${{env.BUILD_TYPE}}

      - name: Import Project
        working-directory: ${{runner.workspace}}/xonix/game
        run: ./godot --headless --editor --quit

      - name: Export
        working-directory: ${{runner.workspace}}/xonix/game
        run: |
          mkdir "../export"
          ./godot --headless --export-release "${{matrix.edition}}" "../export/${{matrix.output}}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: xonix
          path: export
