name: Web

on: [ push, pull_request ]

env:
  BUILD_TYPE: "Release"
  GODOT_VERSION: "4.1.1"
  GODOT_EDITION: "linux.x86_64"
  # https://github.com/godotengine/godot/blob/4.1/.github/workflows/web_builds.yml
  EM_VERSION: "3.1.18"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ">=3.10"

      - name: Cache Godot
        uses: actions/cache@v3
        with:
          path: |
            _deps
            build/_deps
            Godot*.zip
          key: godot-${{env.GODOT_VERSION}}-em-${{env.EM_VERSION}}-web-${{env.GODOT_EDITION}}

      - name: Cache Export Templates
        uses: actions/cache@v3
        with:
          path: Godot*export_templates.tpz
          key: godot-${{env.GODOT_VERSION}}-export-templates

      - name: Install Dependencies
        run: pip install requests

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: ${{env.EM_VERSION}}

      - name: Download Editor
        run: python scripts/download.py editor --godot-version "${{env.GODOT_VERSION}}" --godot-edition "${{env.GODOT_EDITION}}"

      - name: Prepare Editor
        id: editor
        shell: bash
        run: |
          chmod +x "./Godot_v${{env.GODOT_VERSION}}-stable_linux.x86_64"
          echo "PATH=$PWD/Godot_v${{env.GODOT_VERSION}}-stable_linux.x86_64" >> "$GITHUB_OUTPUT"

      - name: Download Export Templates
        run: python scripts/download.py export-templates --godot-version "${{env.GODOT_VERSION}}" --no-install

      - name: Prepare Build (Host)
        run: cmake -E make_directory build

      - name: Configure CMake (Host)
        working-directory: ${{runner.workspace}}/xonix/build
        run: cmake .. -DCMAKE_BUILD_TYPE="${{env.BUILD_TYPE}}"

      - name: Build (Host)
        working-directory: ${{runner.workspace}}/xonix/build
        run: cmake --build . --config ${{env.BUILD_TYPE}}

      - name: Configure CMake
        run: emcmake cmake . -DCMAKE_BUILD_TYPE="${{env.BUILD_TYPE}}"

      - name: Build
        run: cmake --build . --config ${{env.BUILD_TYPE}}

      - name: Import Project
        shell: bash
        working-directory: ${{runner.workspace}}/xonix/game
        run: ${{steps.editor.outputs.PATH}} --headless --editor --quit || true

      - name: Export
        shell: bash
        working-directory: ${{runner.workspace}}/xonix/game
        run: |
          mkdir "../export"
          ${{steps.editor.outputs.PATH}} --headless --export-release "web" "../export/index.html" || true

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: 'export'

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: xonix-web
          path: export
